apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: emreeryigit/users
      context: nest-kafka
      docker:
        dockerfile: apps/users/Dockerfile
      sync:
        manual:
          - src: apps/users/src/**/*.ts
            dest: .
    - image: emreeryigit/products
      context: nest-kafka
      docker:
        dockerfile: apps/products/Dockerfile
      sync:
        manual:
          - src: apps/products/src/**/*.ts
            dest: .
    - image: emreeryigit/orders
      context: nest-kafka
      docker:
        dockerfile: apps/orders/Dockerfile
      sync:
        manual:
          - src: apps/orders/src/**/*.ts
            dest: .
