apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: emreeryigit/users
      context: nest-kafka
      docker:
        dockerfile: apps/users/Dockerfile
      sync:
        manual:
          - src: "apps/users/src/**/*.ts"
            dest: .
          - src: "libs/common/src/**/*.ts"
            dest: .
    - image: emreeryigit/products
      context: nest-kafka
      docker:
        dockerfile: apps/products/Dockerfile
      sync:
        manual:
          - src: "apps/products/src/**/*.ts"
            dest: .
          - src: "libs/common/src/**/*.ts"
            dest: .
    - image: emreeryigit/orders
      context: nest-kafka
      docker:
        dockerfile: apps/orders/Dockerfile
      sync:
        manual:
          - src: "apps/orders/src/**/*.ts"
            dest: .
          - src: "libs/common/src/**/*.ts"
            dest: .
    - image: emreeryigit/expiration
      context: nest-kafka
      docker:
        dockerfile: apps/expiration/Dockerfile
      sync:
        manual:
          - src: "apps/expiration/src/**/*.ts"
            dest: .
          - src: "libs/common/src/**/*.ts"
            dest: .
    - image: emreeryigit/payments
      context: nest-kafka
      docker:
        dockerfile: apps/payments/Dockerfile
      sync:
        manual:
          - src: "apps/payments/src/**/*.ts"
            dest: .
          - src: "libs/common/src/**/*.ts"
            dest: .
