apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: emreeryigit/expiration
          env:
            - name: REDIS_HOST
              value: expiration-redis-srv
            - name: KAFKA_URL
              value: "kafka-srv:9092"
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
